# Generated by Django 2.0.7 on 2018-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_translator',
            field=models.BooleanField(default=True),
        ),
    ]
