# Generated by Django 2.0.7 on 2018-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[(0, 'english'), (1, 'kurdi'), (2, 'german'), (3, 'espanol'), (4, 'russian')], max_length=2),
        ),
    ]
