# Generated by Django 2.0.7 on 2018-07-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='symbols_ammount',
            new_name='symbols_amount',
        ),
    ]
