# Generated by Django 2.0.7 on 2018-08-22 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'last_change', 'ordering': ('published',)},
        ),
        migrations.AlterModelOptions(
            name='articlecase',
            options={'get_latest_by': 'published', 'ordering': ('published',)},
        ),
        migrations.AddField(
            model_name='article',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articlecase',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
