# Generated by Django 2.0.7 on 2018-08-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0002_auto_20180822_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
