# Generated by Django 2.0.7 on 2018-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0002_auto_20180719_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[(0, 'english'), (1, 'kurdi'), (2, 'german'), (3, 'espanol'), (4, 'russian')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='translator',
            name='language',
            field=models.IntegerField(choices=[(0, 'english'), (1, 'kurdi'), (2, 'german'), (3, 'espanol'), (4, 'russian')], default=0, max_length=5),
        ),
    ]
