# Generated by Django 2.0.7 on 2018-07-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0002_auto_20180708_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
