# Generated by Django 2.0.7 on 2018-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0003_auto_20180719_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('0', 'english'), ('1', 'kurdi'), ('2', 'german'), ('3', 'espanol'), ('4', 'russian')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='logger',
            name='decision',
            field=models.CharField(blank=True, choices=[('0', 'new'), ('1', 'update'), ('2', 'user-choice')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='language',
            field=models.CharField(choices=[('0', 'english'), ('1', 'kurdi'), ('2', 'german'), ('3', 'espanol'), ('4', 'russian')], default=0, max_length=5),
        ),
    ]
