# Generated by Django 2.0.7 on 2018-07-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0003_auto_20180708_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='translator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tr_helper.Translator'),
        ),
    ]
