# Generated by Django 2.0.7 on 2018-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0005_auto_20180720_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlog',
            name='article',
            field=models.CharField(max_length=100),
        ),
    ]
