# Generated by Django 2.0.7 on 2018-07-07 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0005_auto_20180708_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr_helper.Translator'),
        ),
    ]
