# Generated by Django 2.0.7 on 2018-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0006_auto_20180708_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_eng',
            field=models.BooleanField(default=True),
        ),
    ]
