# Generated by Django 2.0.7 on 2018-07-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tr_helper', '0007_article_is_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstatistic',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr_helper.Translator'),
        ),
    ]
