# Generated by Django 2.0.5 on 2018-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurd', models.CharField(max_length=20)),
                ('ru', models.CharField(max_length=20)),
                ('info', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
